name: Post Word of the Day

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 11:00 AM IST (5:30 AM UTC)
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Allows updating word_list.csv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ Ensures it pulls the latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python bot.py

      - name: Commit and Push Updated CSV
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          
          # Stage changes
          git add word_list.csv

          # Check if there are any changes after staging
          if git diff --cached --quiet; then
            echo "No changes in word_list.csv, skipping commit."
            exit 0
          fi

          git commit -m "Removed posted word from CSV"
          git push
